### ISSUE TITLE
Crash on Markdown language highlighting

### ISSUE THREAD

**Issue by polpielladev** [krzyzanowskim/STTextView-Plugin-Neon#6]
Hi! 👋 

First of all, thanks for the great work on `STTextView` and the `Neon` plugin, it's amazing!

I have run into an issue recently where if I use the `NeonPlugin` to parse and highlight `Markdown` Strings, I get a crash on this line of the `Coordinator` file of the plugin:

![CleanShot 2024-02-11 at 23 32 10@2x](https://github.com/krzyzanowskim/STTextView-Plugin-Neon/assets/24246926/7dec6e30-cf58-4292-a9b4-425bcaccf76d)

I have done a bit of digging and it looks like there are [no highlight queries for the markdown language](https://github.com/krzyzanowskim/tree-sitter-xcframework/tree/main/Sources/TreeSitterResource/LanguageResources), which explains the crash. Could this be that there is an issue with the markdown tree sitter or its build process? 

Not entirely sure how to regenerate the tree sitter to test it myself, but I am happy to help out to look into it if you know the cause?

**Comment by krzyzanowskim** [comment]
ha! It does not provide a highlight query. There is an issue https://github.com/ikatyang/tree-sitter-markdown/issues/23 and it looks like we should get it from https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/markdown

**Comment by krzyzanowskim** [comment]
[tree-sitter-xcframework 0.208.5](https://github.com/krzyzanowskim/tree-sitter-xcframework/releases/tag/0.208.5) should fix that
