### ISSUE TITLE
No colouring for HTML and Markdown

### ISSUE THREAD

**Issue by jeanetienne** [krzyzanowskim/STTextView-Plugin-Neon#9]
Hi Marcin and team, thank you for this package!

I’ve been playing with this plug-in on a pet project and it seems HTML and Markdown don’t work in terms of syntax colouring. If I swap the language to Swift or CSS it works fine but not for those two (perhaps others?). 
are you aware of a limitation or am I “holding it wrong”?

Thanks for your help!

**Comment by krzyzanowskim** [comment]
the plugin needs some love. I'm using https://github.com/krzyzanowskim/tree-sitter-xcframework as a tree-sitter dependency, and this is the source of missing/not working syntax. It's not trivial to update that package and I'm thinking whether maybe there is a better source of tree-sitter to use by this plugin.

If that's something you'd like to try, it's good idea investigate if eg. https://github.com/simonbs/TreeSitterLanguages is easy to integrate instead.

**Comment by jeanetienne** [comment]
Thank you for the super quick reply!
I'll report back if I make any progress but I can't promise anything as I feel like this is a bit too far over my expertise level 😅

**Comment by krzyzanowskim** [comment]
more languages just landed

![Screenshot 2024-08-06 at 02 52 15](https://github.com/user-attachments/assets/01496521-c187-41ad-af3b-eaf64f94839d)

**Comment by jeanetienne** [comment]
Awesome, thank you!
